# The playbook /home/bob/playbooks/fruits.yml 
# currently runs an echo command to print a fruit name. 
# Add a loop directive (i.e with_items) in the task to print all fruits defined under the fruits variable.

# cd /home/bob/playbooks
####
###```
###ansible-playbook -i localhost, fruits.yml -vv
##```
####


##########################
#####
###
##--- ##
##- name: 'Print fruits'
## hosts: localhost
##  connection: local
##  vars:
#    fruits:                          ##
#      - Apple
#      - Banana                      ##
#      - Grapes                      ##
#      - Orange                      ##
 # tasks:                            ##
#    - command: 'echo Apple'         ##
    ####################################
---
- name: 'Print fruits'
  hosts: localhost
  connection: local
  vars:
    fruits:
      - Apple
      - Banana
      - Grapes
      - Orange
  tasks:
    - command: 'echo "{{ item }}"'
      with_items: '{{ fruits }}'
