# Create an Ansible role called package under /home/bob/playbooks/roles directory on student-node. 
# It should install a package called nginx and should start its service as well.



# Further consume this role in /home/bob/playbooks/role.yml playbook so that this role can be applied on node01

# First Steps to create workspace for lab's file
# cd /home/bob/playbooks/roles/
# ansible-galaxy init package
# vi /home/bob/playbooks/roles/package/tasks/main.yml


---
# tasks file for nginx
- name: Install Nginx
  ansible.builtin.package:
    name: nginx 
    state: latest
- name: Start Nginx Service
  ansible.builtin.service:
    name: nginx 
    state: started


# Now modify the /home/bob/playbooks/role.yml playbook so that it looks like as below:

---
- hosts: node01
  become: true
  roles:
    - roles/package

# To run this playbook, run the following commands:
```
cd /home/bob/playbooks/
ansible-playbook -i inventory role.yml

```
